### ISSUE TITLE
Do these mods already optimize the game

### ISSUE THREAD

**Issue by User4716** [Steveplays28/noisium#11]
I have these two mods installed that are not available in Modrinth and I am not sure if I need them with this mod
https://www.curseforge.com/minecraft/mc-mods/chunk-sending-forge-fabric
https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save

**Comment by Steveplays28** [comment]
Hi, those mods do completely different things, compared to Noisium, so it's fine if you install them alongside Noisium.
