### ISSUE TITLE
[Question] Compatible with Forge and Canary (Forge port of Lithium) using Sinytra Connector?

### ISSUE THREAD

**Issue by DarthCaesium** [Steveplays28/noisium#12]
Hi! I was wondering if this works on Forge using Sinytra Connector. Would it work without problems using Forge biome mods and Forge performance mods?

**Comment by Steveplays28** [comment]
Hi DarthCaesium, it might work. Pretty sure Sinytra Connector loads mixins as normal. I haven't tested it myself though.
You'll have to try it and see.

If Noisium works, it should work fine with any biome mod, as long as they don't modify the noise generation step.
Keep in mind that there's a small issue with Lithium (see #10) currently, related to underwater creatures, which you might run into.

There's also an [unofficial Forge port](https://modrinth.com/mod/noisium-(unofficial-forge-port)) for 1.19.2, if you're using that Minecraft version, by chance.
Thanks for checking out Noisium.
