### ISSUE TITLE
Incompatibility with latest versions of Lost Cities when playing via Sinytra Connector

### ISSUE THREAD

**Issue by StardustPassingBy** [Steveplays28/noisium#13]
I've been using Noisium on Forge (4.7.2.0, running Minecraft 1.20.1) via the Sinytra connector and it doesn't seem to have any issues except an incompatibility with the latest versions (1.20.7.1.1 and 1.20.7.1.0) of Lost Cities for forge. I tried reporting on the Lost Cities issues page first, but the mod dev said it's an issue on Noisium's end with the mod reducing visibility. The specific error is "NoiseChunkGeneratorMixin from mod noisium cannot reduce visibiliy of PUBLIC target method."

Here's a latest.log with only Sinytra Connector, Connector Extras, The Lost Cities, and Noisium active:

[latest(13).log](https://github.com/Steveplays28/noisium/files/14220899/latest.13.log)

I realize that this mod is Fabric first and foremost so it's a long shot, but I figure it's worth a try. :)

**Comment by Steveplays28** [comment]
Hi Stardust, I think that's because Lost Cities has an access widener on a method I mix into, causing a crash.
I'll see what I can do about it.

**Comment by Steveplays28** [comment]
Fixed in commit https://github.com/Steveplays28/noisium/commit/b2f5b51d1126379294c0f0c57fb97347b6228395.

**Comment by Steveplays28** [comment]
The fix for this issue has been released in [`v2.0.0`](https://github.com/Steveplays28/noisium/releases/tag/v2.0.0%2Bmc1.20.x).
