### ISSUE TITLE
Fluids not rendered until player interaction (right click)

### ISSUE THREAD

**Issue by ghost** [Steveplays28/noisium#16]
At times, certain parts of lava or water streams can be rendered invisible. Occurs throughout both overworld and nether. Not sure if this is a mod compatibility error.
Images:
![image](https://github.com/Steveplays28/noisium/assets/157556010/45240556-293c-4cdb-abcc-c9eaff2e46ab)
Part of lava stream is invisible.
![image](https://github.com/Steveplays28/noisium/assets/157556010/cc03bdf0-730d-4ac8-b1c0-85323d7e32a9)
Stays invisible after block update.

**Mods list:**
Health Indicator TXF https://modrinth.com/mod/health-indicator-txf
Mod Menu https://modrinth.com/mod/modmenu
NBT AutoComplete https://modrinth.com/mod/nbt-autocomplete
Dynamic FPS https://modrinth.com/mod/dynamic-fps 
Xaero’s Worldmap https://modrinth.com/mod/xaeros-world-map 
Zoomify https://modrinth.com/mod/zoomify 
Better Statistics https://modrinth.com/mod/better-stats 
BetterF3 https://modrinth.com/mod/betterf3 
Debugify https://modrinth.com/mod/debugify 
Chat Heads https://modrinth.com/mod/chat-heads 
More Culling https://modrinth.com/mod/moreculling 
Entity Culling https://modrinth.com/mod/entityculling 
ModernFix https://modrinth.com/mod/modernfix 
FerriteCore https://modrinth.com/mod/ferrite-core 
Peek https://modrinth.com/mod/peek 
Immediately Fast https://modrinth.com/mod/immediatelyfast 
Status Effect Bars https://modrinth.com/mod/status-effect-bars 
Who Am I? https://modrinth.com/mod/whoami
Concurrent Chunk Management Engine https://modrinth.com/mod/c2me-fabric 
Thread Tweak https://modrinth.com/mod/threadtweak 
Lazy Language Loader https://modrinth.com/mod/lazy-language-loader 
AppleSkin https://modrinth.com/mod/appleskin
Simple Item Editor https://modrinth.com/mod/simple-item-editor 
Screenshot to Clipboard https://modrinth.com/mod/screenshot-to-clipboard 
Very Many Players https://modrinth.com/mod/vmp-fabric 
Xaero’s Minimap (Fair Play) https://modrinth.com/mod/xaeros-minimap-fair 
Better Mount HUD https://modrinth.com/mod/better-mount-hud 
CustomHud https://modrinth.com/mod/customhud  
Krypton https://modrinth.com/mod/krypton 
Lithium https://modrinth.com/mod/lithium  
Bad Optimizations https://modrinth.com/mod/badoptimizations 
Fast Quit https://modrinth.com/mod/fastquit 
Fast IP Ping https://modrinth.com/mod/fast-ip-ping  
Paginated Advancements https://modrinth.com/mod/paginatedadvancements 
Minecraft Capes https://modrinth.com/mod/minecraftcapes 
Your Options Shall be Respected https://modrinth.com/mod/yosbr 
e4mc https://modrinth.com/mod/e4mc 
LazyDFU https://modrinth.com/mod/lazydfu 
Totem Small Pop https://modrinth.com/mod/cpvp 
Sodium https://modrinth.com/mod/sodium 
Gamma Shifter https://modrinth.com/mod/gamma-shifter 
NoFog https://modrinth.com/mod/no_fog 
Noisium https://modrinth.com/mod/noisium 

Using dark ui resource pack from vanillatweaks.net

**Comment by SirBob27** [comment]
This problem was no longer visible when opening a new world without noisium installed.

**Comment by ghost** [comment]
Sorry, accidentally closed issue

**Comment by ghost** [comment]
Important to note, player still gets set on fire in invisible lava. I'd assume invisible water would have similar effects, but I have yet to test it.

**Comment by Steveplays28** [comment]
Could be due to #10, for which I opened an issue in Lithium's repository.

**Comment by ghost** [comment]
Definitely possible, but entities treat the unrendered sections as normal lava/water, instead of simply going through it. It's kind of like the opposite effect; the client just doesn't render it. Not tested on a server with noisium installed.

**Comment by ghost** [comment]
I'll try to create a testing world in which I can run through the issue more thoroughly.

**Comment by ghost** [comment]
![image](https://github.com/Steveplays28/noisium/assets/157556010/d20295f4-e94e-40f3-b292-7d3e03eabb4c)
Strangely enough, after spawning an entity using a spawn egg on an invisible flowing lava, the lava becomes fully visible again and does not revert to its invisible state.
<img width="1440" alt="Screenshot 2024-02-22 at 3 31 10 PM" src="https://github.com/Steveplays28/noisium/assets/157556010/a250e811-63c3-477b-a038-0ff4ee2a1c64">

**Comment by ghost** [comment]
Apparently needs to be a player interaction. Using /summon does not cause the lava to render. Placing armor stands using an item works.

**Comment by ghost** [comment]
Something I forgot to check earlier, but you actually only need to right click where the invisible fluid is. No entity spawning needed. Left clicking does nothing.

**Comment by Steveplays28** [comment]
This should be fixed in [`v2.0.2`](https://github.com/Steveplays28/noisium/releases/latest), since I've added Lithium compatibility.
Let me know if any (other) issues arise.

**Comment by ghost** [comment]
Thanks! The fix seems to be working perfectly.

**Comment by Steveplays28** [comment]
Awesome, glad to hear.
