### ISSUE TITLE
1.20.1 Neoforge 47.1.101 ``Crash on Startup``

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Steveplays28/noisium#17]
I did modpack upkeep and now I can't launch I suspect based prior reports it has to do with lost cities anyways here is log.

https://mclo.gs/XbMdM8w

The log says wrong version but that actually wasn't an issue till after this latest string of updates.

- Domum Ornamentum [1.20-1.0.170-BETA (Updated)
- FTBQuestsOptimizer [1.2.2-1.20.1] (Updated)
- GeckoLib 4 [4.4.4] (Updated)
- Iron Bookshelves [1.20.1-1.3.0-forge] (Updated)
- LostCities [1.20-7.1.3 (Updated)
- LostSouls [1.20-4.0.3 (Updated)
- MineColonies [1.20.1-1.1.510-BETA] (Updated)
- Philips Ruins [3.4] (Updated)
- Silent Gear [3.6.0 (Updated)
- Structurize [1.20.1-1.0.712-BETA] (Updated)

I suspect one of this causing issues.

Due to time constraints I cannot test it so I am simply removing mod for now.

**Comment by Steveplays28** [comment]
You're using Noisium for 1.19.2 on 1.20.1, that's not going to work it seems.
Are you using the [unofficial Forge port of Noisium](https://www.curseforge.com/minecraft/mc-mods/noisium-unofficial-forge-port) by [coco_31240](https://www.curseforge.com/members/coco_31240)?

Could you try using the new multiloader version for Minecraft 1.20.x, when you have time?
You can download it from the [actions](https://github.com/Steveplays28/noisium/actions/runs/8011618324) tab.

**Comment by P3rf3ctXZer0** [comment]
I am using the multiloader version
I got it from here. https://modrinth.com/mod/noisium is this not correct?

**Comment by Steveplays28** [comment]
Try the file in the [latest run](https://github.com/Steveplays28/noisium/actions/runs/8011618324) if you haven't already.
There's no references to 1.19 in this project anywhere so it's odd that it's saying that in the logs.

Would you mind also posting your normal `latest.log`?

**Comment by P3rf3ctXZer0** [comment]
> Try the file in the [latest run](https://github.com/Steveplays28/noisium/actions/runs/8011618324) if you haven't already. There's no references to 1.19 in this project anywhere so it's odd that it's saying that in the logs.
> 
> Would you mind also posting your normal `latest.log`?

No problem; I need a bit too fix my devices (I didn't lease ips and now 21 devices got shuffled.)

**Comment by P3rf3ctXZer0** [comment]
Here is the latest.log https://mclo.gs/nh2VFAx I even fresh generated it.

**Comment by P3rf3ctXZer0** [comment]
This the official jar you recommended 
![AnyDesk_TBqz7dJk3c 1](https://github.com/Steveplays28/noisium/assets/10351221/21e6c800-aad7-42e3-9142-19427504d925)

**Comment by Steveplays28** [comment]
I don't see any mention of Noisium in the log. At the bottom of the log it shows a datapack error, try removing/fixing that datapack and see if the server loads.

**Comment by P3rf3ctXZer0** [comment]
okay.

**Comment by P3rf3ctXZer0** [comment]
okay so you are right ... why did the crashlog blame ... ugh thanks for your time.

**Comment by Steveplays28** [comment]
No problem, have fun playing!
