### ISSUE TITLE
incompatiblity with c2me

### ISSUE THREAD

**Issue by Epik0rangutan** [Steveplays28/noisium#18]
![image](https://github.com/Steveplays28/noisium/assets/163749224/69db5f8d-6f90-4a10-9606-e344664ef927)

What in the actual fuck is happening please save me

**Comment by Puhpine4915** [comment]
Have you read the FAQ in the distant horizons discord server? Specifically about c2me

**Comment by Steveplays28** [comment]
Hi @Epik0rangutan, as Puhpine said above, please read the compatibility FAQ (C2ME section specifically) in the Distant Horizons Discord server.
This issue is related to compatibility between C2ME and DH, not Noisium.
