### ISSUE TITLE
Incompatibility with NeoForge 1.20.2-1.20.4

### ISSUE THREAD

**Issue by waddon1** [Steveplays28/noisium#20]
The mod says it supports NeoForge and 1.20.4 however it fails to launch on a NeoForge 1.20.4 server

**Comment by Steveplays28** [comment]
Hi, thanks for the report. That's not good, to say the least.
Can you send your `latest.log`?

**Comment by waddon1** [comment]
https://gist.github.com/waddon1/1c7485a31b09b43a9cfff5704ef89081

**Comment by Steveplays28** [comment]
Thanks!
Seems like it works on Forge, but on NeoForge it doesn't, because the dependency ID is `neoforge` instead of `forge`.

**Comment by Steveplays28** [comment]
NeoForge apparently cut support for Forge mods after 1.20.1, so I'll have to do some deeper diving.

**Comment by Steveplays28** [comment]
Fixed in [`v2.0.1`](https://github.com/Steveplays28/noisium/releases/tag/v2.0.1%2Bmc1.20.x).
