### ISSUE TITLE
Incompatibility with Mine Cells

### ISSUE THREAD

**Issue by ZiLenTz** [Steveplays28/noisium#22]
Hi, I've been using this mod for a while with no issue and it works great.
However, teleporting to one of [Mine Cells](https://modrinth.com/mod/minecells) dimensions, _Promenade of The Condemned_ or _minecells:promenade_, will result in disconnecting the player and crashing the server.

To be specific, that dimension can't be generated with Noisium.
Also, based on a crash log, it seems like the issue is related to _NoiseChunkGenerator_ from Noisium.
Right now I have to play without Noisium since removing it solved the issue.

Crash Log: https://mclo.gs/QFFDEI0

Minecraft 1.20.1
Fabric Loader 0.15.7
Noisium 2.0.1
Mine Cells 1.7.2

Portal to Promenade of The Condemned (minecells:promenade)
![2024-04-07_00 36 44](https://github.com/Steveplays28/noisium/assets/148383597/ad2f1e79-a87f-4066-9ea2-72cb5a00f5de)

**Comment by Steveplays28** [comment]
Hi ZiLenTz, thanks for the report. I'll look into this issue!

**Comment by HaXrDEV** [comment]
Reverting Noisium back to v1.0.2 seems to solve the issue for me.

**Comment by mim1q** [comment]
Hey, Mine Cells dev here, I'd be happy to help try and figure out this issue and fix it if the fault is on my end 😅 

I believe the issue might be related to [one of my custom density functions](https://github.com/mim1q/MineCells/blob/1.20.x-1.8.0/src/main/java/com/github/mim1q/minecells/world/densityfunction/CliffDensityFunction.java), where I sample a noise in a not-so-conventional way. (not the best at writing that type of thing, so I'd appreciate any suggestions for improvements in the code, and a possible way to fix this crash!)

**Comment by Steveplays28** [comment]
@mim1q Hi mim1q, thanks for reaching out. I haven't figured out why it occurs on my end (when it doesn't with vanilla + MineCells).
I'll do some investigating and write back.

**Comment by ZiLenTz** [comment]
Really appreciate both of your responses!

Thanks for your hard work!

**Comment by Steveplays28** [comment]
I found where the issue happens. The chunk section locking goes out of bounds when accessing the arrays of chunk sections in `noisium$populateNoiseInject`. For some reason it's looping over more chunk sections than it's allocating to the array.
Might be an issue on my end, will take a further look

**Comment by Steveplays28** [comment]
@ZiLenTz @mim1q Should be fixed in [`v2.0.3`](https://github.com/Steveplays28/noisium/releases/latest).
