### ISSUE TITLE
Crash when creating new chunk in ad_astra dimension

### ISSUE THREAD

**Issue by mberlin1** [Steveplays28/noisium#25]
Game verison: 1.20.1
Noisum version: noisium-forge-2.0.2+mc1.20-1.20.1

how to reproduce:
take a new world from monumental's 1.20.1 modpack.
spawn yourself a launchpad and tier 2 rocket
spawn yourself 64 desh ingots and 64 desh plates, 64 steel ingots and 64 iron plates
hop into the rocket, blast off
in earth orbit, click on the plus sign and try to build a space station. Crash.
Crash log attached.
[new 1.txt](https://github.com/Steveplays28/noisium/files/15032325/new.1.txt)

**Comment by Steveplays28** [comment]
You ran out of memory according to the stack trace. Could you try it with more memory, and with a minimal set of mods?

**Comment by mberlin1** [comment]
Ran out of memory? it's running with 24 gigabytes of ram.

**Comment by Steveplays28** [comment]
I don't see anything referencing Noisium in that log file, nor do I see Noisium's loading log message.
As said, would you mind trying with a minimal set of mods to ensure that Noisium is the issue?

**Comment by mberlin1** [comment]
Sure, i'll get you a log.  If you have a suggestion for whose code might be
involved in resolving the chunk creation and subsequent crash, i'm open to
suggestions.

**Comment by Steveplays28** [comment]
Just realized that this might be the same issue holmraven reported in my Discord server one and a half weeks ago.
I'll do some further investigating.

**Comment by Luviam** [comment]
Tested this with a fresh profile and only Ad Astra, Noisium, and lib mods. I Also crashed but not due to memory. Here's my log if it helps.
[latest.log](https://github.com/Steveplays28/noisium/files/15075076/latest.log)

**Comment by 3dEADto2** [comment]
I have the same crash with create: dreams and desires or the graveyard (fabric 1.20.1, noisium ver. 2.0.2)
[latest.log](https://github.com/Steveplays28/noisium/files/15084601/latest.log)
[crash-2024-04-24_02.59.37-server.txt](https://github.com/Steveplays28/noisium/files/15084602/crash-2024-04-24_02.59.37-server.txt)

**Comment by Steveplays28** [comment]
These issues all seem like the same issue as in #22.
Might change the array back into a `Set`/`ArrayList`, since whatever check Minecraft is doing to give the array its initial size is incompatible with mods.

**Comment by Steveplays28** [comment]
Fixed in [`v2.0.3`](https://github.com/Steveplays28/noisium/releases/latest). Thanks for the report!
