### ISSUE TITLE
Update to 1.20.6

### ISSUE THREAD

**Issue by BlueGradientHorizon** [Steveplays28/noisium#27]
Hello. Can you update Noisium to 1.20.6, please?

**Comment by Steveplays28** [comment]
Hi, I'll update Noisium (and my other mods) to 1.20.5/1.20.6 when I have time.
For now, you might be able to get it working using a [dependency override](https://fabricmc.net/wiki/tutorial:dependency_overrides).

**Comment by DearFox** [comment]
> Hi, I'll update Noisium (and my other mods) to 1.20.5/1.20.6 when I have time. For now, you might be able to get it working using a [dependency override](https://fabricmc.net/wiki/tutorial:dependency_overrides).

That is, it should work fine on 1.20.5 and 1.20.6?  Just need to change the file inside the mod?  Or do I still need to re-build it with new dependencies?

**Comment by Steveplays28** [comment]
@DearFox You can do either of those options. A dependency override is the third option. If you use a dependency override, you won't have to rebuild the mod. You can just force Fabric/Quilt to load the mod anyway. The wiki page I linked shows exactly how to set them up.

**Comment by NotAGanesh** [comment]
@Steveplays28 Now Time to Update! Because i want to update my modpack

**Comment by Steveplays28** [comment]
@NotAGanesh Hi, feel free to add the mod and a loader override, as said above.
Again, I'll update the mod when I have time.

**Comment by Steveplays28** [comment]
I've updated Noisium to Minecraft 1.20.6, in release [`v2.1.0`](https://github.com/Steveplays28/noisium/releases/latest).
