### ISSUE TITLE
Mark Biospherical Expansion as incompatible (soft breaks/warning)

### ISSUE THREAD

**Issue by Steveplays28** [Steveplays28/noisium#31]
https://www.curseforge.com/minecraft/mc-mods/biospherical-expansion

Biospherical Expansion causes subtle issues, such as feature order cycle crashes when used with Noisium and/or other world generation mods. This is likely due to the `@Overwrite`s in Biospherical Expansion's mixins.
[crash log](https://mclo.gs/wvhMqnN)

Thank you to rocketthief in my Discord server for the [report](https://discord.com/channels/746681304111906867/768404604722348032/1251149666188394507).

**Comment by Steveplays28** [comment]
I've marked Biospherical Expansion as incompatible in [`v2.3.0`](https://github.com/Steveplays28/noisium/releases/latest).

**Comment by Gavin456b** [comment]
Try https://www.curseforge.com/minecraft/mc-mods/feature-recycler 

May get rid of the feature order cycle crashes

**Comment by Steveplays28** [comment]
@Gavin456b Thanks for the suggestion, I'll pin this issue for those that run into this.
