### ISSUE TITLE
Update for 1.21.1

### ISSUE THREAD

**Issue by Avakining** [Steveplays28/noisium#36]
As far as I can tell, this should involve minimal (if any) changes

**Comment by Steveplays28** [comment]
Hi, I'll update Noisium when I have time. For now you could use a Fabric/Quilt loader override or edit the JAR's metadata.

**Comment by Steveplays28** [comment]
I've updated Noisium to Minecraft 1.21.1 in [`v2.3.0`](https://github.com/Steveplays28/noisium/releases/latest).
