### ISSUE TITLE
Steve's sleep instead of Noisium on Modrinth page

### ISSUE THREAD

**Issue by tajemniktv** [Steveplays28/noisium#37]
Hey, just a quick notice, you migt've accidentaly uploaded your other mod on Noisium page:pp
@Steveplays28 

https://modrinth.com/mod/noisium/changelog

**Comment by Steveplays28** [comment]
I'm fixing it, I was wondering where that release went. Thanks for the heads up

**Comment by Steveplays28** [comment]
I removed the releases from Noisium's Modrinth and CurseForge pages.
