### ISSUE TITLE
1.21.1无法启动游戏

### ISSUE THREAD

**Issue by 258654aun** [Steveplays28/noisium#38]
1.21.1使用NEOFORGE 21.1.50启动游戏时崩溃。
MOD版本为2.3.0
[错误报告-2024-9-12_18.34.08.zip](https://github.com/user-attachments/files/16977675/-2024-9-12_18.34.08.zip)

**Comment by Weigurde** [comment]
update your java to 21

**Comment by 258654aun** [comment]
使用JAVA21仍然无法启动
[错误报告-2024-9-12_20.10.27.zip](https://github.com/user-attachments/files/16978902/-2024-9-12_20.10.27.zip)

**Comment by Steveplays28** [comment]
@258654aun Hi, could you redownload Noisium?
I accidentally uploaded one of my other mods to Noisium's pages a week ago, which seems like what you downloaded. Apologies for that.
