### ISSUE TITLE
[Question] Usage in Modpacks

### ISSUE THREAD

**Issue by NXTler** [Steveplays28/noisium#39]
Greetings,
I'm currently working on a VulkanMod based performance Modpack and would like to include this particular mod as well. However, I haven't found any information about the usage in Modpacks in the description.
What am I allowed to do?

**Comment by Steveplays28** [comment]
Hi NXTler, you're allowed to use Noisium in modpacks!
Noisium is uploaded to Modrinth and CurseForge, which automatically means you can include it in Modrinth/CurseForge modpacks. See also: [Modrinth modpack permission documentation](https://docs.modrinth.com/modpacks/permissions).

If you want to modify Noisium you have to abide by the license, [LGPLv3](https://github.com/Steveplays28/noisium/blob/1.20-1.20.1/LICENSE).
If you make a modpack on GitHub (e.x. using Packwiz) that's allowed as well by the license.

Let me know if you have any further questions. Thank you for checking out Noisium!
