### ISSUE TITLE
Clarify vanilla parity in description

### ISSUE THREAD

**Issue by sisby-folk** [Steveplays28/noisium#4]
Hello! Just bumped into the modrinth page - can you clarify whether worldgen output is 1:1 with vanilla explicitly in descriptions?

It'd also be good to know whether the generation is faster as in "it takes less time to generate x chunks, but consumes the same amount of resources" (as in a scheduling optimization), or as in "it takes less resources to generate x chunks, and therefore takes less time" (as in a cycle optimization) - as that would change whether the impact to framerate stability in singleplayer is negative or positive.

 Thanks!

**Comment by Steveplays28** [comment]
Hey, I'll try to add some docs to the readme this weekend.
Also need to add some benchmarks, if anyone watching this thread has benchmarks feel free to send them in the [Discord server](https://discord.gg/KbWxgGg)!

**Comment by Steveplays28** [comment]
I added your suggestions to the readme, thanks again.
Going to add some benchmarks as well.

**Comment by PoneyClairDeLune** [comment]
Another question: Does "vanilla parity" mean all the terrain (caves, etc) will stay the same as vanilla?

**Comment by Steveplays28** [comment]
Hi PoneyClairDeLune, yes. Vanilla parity means *everything* stays the same, when comparing vanilla vs Noisium. All the block generation is the same, but the placement of them is optimised, alongside some other minor optimisations. There's currently a bug with Lithium which will cause minor issues with submerged entities, but that's being fixed on Lithium's side.
