### ISSUE TITLE
[bug] crash when start

### ISSUE THREAD

**Issue by vocaloidkiss** [Steveplays28/noisium#43]
[crash-2024-10-05_16.51.22-client.txt](https://github.com/user-attachments/files/17265613/crash-2024-10-05_16.51.22-client.txt)

**Comment by Steveplays28** [comment]
Hi, please redownload Noisium's latest version. You downloaded Noisium when I accidentally pushed a build of Realistic Sleep to Noisium's page, instead of Realistic Sleep's page.
See https://github.com/Steveplays28/noisium/issues/38.

**Comment by vocaloidkiss** [comment]
OMG !!!!!!!my buddy you do it again today and we have to try to avoid downloading wrong version!!!!!!!!!

**Comment by Steveplays28** [comment]
Yeah, happened with a different project again a few weeks ago, sorry about that. I've since made a template project which resolves the issue.
I've removed the versions from Noisium's pages, you shouldn't run into this issue again.
