### ISSUE TITLE
Weird math in description

### ISSUE THREAD

**Issue by JustAlittleWolf** [Steveplays28/noisium#46]
In the description of the mod it is mentioned, that
> In the best case measured so far, the improvements can be up to a 1.25% speedup per thread when generating new chunks in vanilla Minecraft.

This means, if without the mod a thread can generate 100 chunks per minute, it could generate up to 101.25 chunks per minute with noisium.
Then the description claims that
> With 4 threads, that means that there is a 5% increase in world generation speed in total.

This sounds like the percentage adds up with more threads. Unless the threads boost each others performance further with the mod, this is a mathematically incorrect statement. Assuming without the mod, that 4 threads generate 400 chunks per minute (each one generates 100), and assuming that the mod boosts each thread to 101.25 chunks per minute (as claimed before), the total speed would be 1.25% faster than vanilla (405 chunks per minute), not 5%.

Either 
- noisium boosts each thread by 5%, and the number 1.25% is incorrect (which is supported by the benchmark in the description), 
- noisium boosts each thread by 1.25% and the number 5% is incorrect,
- or threads affect each other in some way, in which case the description lacks an explanation,
- or I made some mistake and this comment is nonsense.

**Comment by Steveplays28** [comment]
You're right, that does not add up. I did not realize that when writing this up.
It should just be 5%, as seen in the benchmarks. Thank you for letting me know!

**Comment by Steveplays28** [comment]
I've redone the benchmarks section in the readme, thanks again!
