### ISSUE TITLE
Minecraft 1.21.4 support

### ISSUE THREAD

**Issue by Steveplays28** [Steveplays28/noisium#47]

**Comment by Riflusso** [comment]
Nothing changed, so you actually can update _fabric.mod.json_, _neoforge.mods.toml_ **supported_minecraft_version** field and branch name

**Comment by Steveplays28** [comment]
Thanks for testing that @Riflusso!

**Comment by Steveplays28** [comment]
Released in [`v2.5.0`](https://github.com/Steveplays28/noisium/releases/latest).
