### ISSUE TITLE
Spawn-chunk limitation

### ISSUE THREAD

**Issue by Disketaa** [Steveplays28/noisium#6]
Greetings! I don't know if is doable or not, and if it can be related to your mod, but is it possible to change how many chunks will generate around worldspawn upon world creation? For my world-type generation might be useful to pre-generate small amount of chunks.

If this thing you don't want to work on, you can delete this request, to so as not to clog issues

**Comment by Steveplays28** [comment]
[FastLoad](https://modrinth.com/mod/fastload) has this functionality, if that's what you mean.

**Comment by Disketaa** [comment]
Probably yes, but I don't sure if this mod gets an update to 1.20.2

**Comment by Disketaa** [comment]
I found mod Ksyxis do this thing
